name: Deploy to DO

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to DO
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 64.227.157.211
          username: root
          key: ${{ secrets.PRIVATESSHKEY }}
          passphrase: ${{ secrets.PARAPHRASE }}
          port: 22
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"
            
            # Explicitly set Node.js version
            nvm use node
            export PATH="$NVM_DIR/versions/node/$(nvm current)/bin:$PATH"

            echo "Node Version:"
            node -v
            echo "NPM Version:"
            npm -v

            cd next-js-deploy
            git pull
            npm install
            npm run build
            pm2 stop all || true
            pm2 start