name: Deploy to DO

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to DO
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 143.110.185.69
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: whoami
